### ISSUE TITLE
weird

### ISSUE THREAD

**Issue by rolexwatch123** [Cerealistic/Cerealistic.github.io#15]
clicking the website link opens the readme
![Screenshot 2023-04-19 8 39 29 AM](https://user-images.githubusercontent.com/120110264/233077380-540d970a-6214-424a-a144-da837ed67d5a.png)

**Comment by Cerealistic** [comment]
yea i made that, just type the real URL

**Comment by rolexwatch123** [comment]
whats the real url

**Comment by Cerealistic** [comment]
What do you want? EaglercraftX, Eaglercraft, or a about:blank cloaker?

**Comment by rolexwatch123** [comment]
eaglerx

**Comment by Cerealistic** [comment]
okay, use https://cerealistic.github.io/CerealLink
