### ISSUE TITLE
Your server

### ISSUE THREAD

**Issue by rolexwatch123** [Cerealistic/Cerealistic.github.io#2]
i cant login to anarchy it is saying i have exeded my login requests

**Comment by Cerealistic** [comment]
what do you mean? Can you please explain more in-depth than you just did? if not, then I can manually register you with a password.

**Comment by Cerealistic** [comment]
And by the way... You are not meant to fork this repo. You are supposed to use the website.

**Comment by rolexwatch123** [comment]
i will delete it can you manually  register me my user is: none

**Comment by rolexwatch123** [comment]
deleted it

**Comment by Cerealistic** [comment]
okay! what do you want you password to be? remember- on login you need to enter the command /login %password%
So please tell my what you want you password to be. I will delete this after registering you.

**Comment by rolexwatch123** [comment]
happy

**Comment by rolexwatch123** [comment]
I want my pass to be: happy

**Comment by Cerealistic** [comment]
Okay! I will not be able to do it now, will do it when I get a chance.

**Comment by rolexwatch123** [comment]
Thx

**Comment by Cerealistic** [comment]
I am so sorry, we could not register you as the server has been closed and is inactive. We are working on a new, better server in an updated version of the game. I will update you once it is finished.

**Comment by rolexwatch123** [comment]
oh cool.

**Comment by rblxcollin** [comment]
I am going to close this issue for now, because like Cereal said, the Server is closed and inactive. We can always reopen it if we have news.
