### ISSUE TITLE
Add font

### ISSUE THREAD

**Issue by altude** [Cerealistic/Cerealistic.github.io#4]
Two things to say here:
 - telling people not to fork your repo completely defeats the purpose of having it on github. people 'stealing' your work is just a part of open-source and they probably just found reasons that they could improve it. while it is rude to pass it off as your own, it is just a part of owning an open-source repo. i **strongly** suggest you remove this clause from your readme.
 - The default font on many browsers ruins the look you are trying to achieve. Depending on the look you are trying to achieve, I suggest adding [Plus Jakarta Sans](https://github.com/tokotype/PlusJakartaSans) or [Fira Code](https://github.com/tonsky/FiraCode). I'd be happy to add this via a PR if you'd like.

**Comment by Cerealistic** [comment]
Feel free to use a pull req, I only have this as a repo because I need to use github pages for hosting. people who fork my repo just rename it and use it instead of using an updated version via this repo. They take my work and pretend that they made it my hosting it themselves and deleting evidence that I made it. If you would like to be a contributor, then respond using that term to this comment.

**Comment by Cerealistic** [comment]
sorry for bad grammer I am literally 12 year old who wants children across the world to have a site to unblock websites.

**Comment by Cerealistic** [comment]
Also, here is an example of some b@st@rd who forked my repo and just edited the readme to put me down. https://github.com/unblockedgames129/COOLBLOCKER

**Comment by altude** [comment]
1. You're way too young to be on GitHub. Go outside and touch grass.
2. You can private it and use [Vercel](https://vercel.app) to host it for free.
3. He's not wrong, its quite immature to tell people not to fork your repo.
Closing this issue because you aren't worthy of a PR.

**Comment by Cerealistic** [comment]
*sigh* everyone doesn't understand...

**Comment by Cerealistic** [comment]
you realize that vercel is blocked on school chromebooks right? That's the only reason I have this public on github. Also, I am not too young to be on github. I am too young to tunnel through my firewall and self-host at home, too young to get a domain, and too young to code apparently.
