### ISSUE TITLE
my district completely blocked replit

### ISSUE THREAD

**Issue by logieboyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy** [Cerealistic/Cerealistic.github.io#6]

**Comment by Cerealistic** [comment]
Sorry for that! I am currently working on a github-based version. It will help you with this problem!

**Comment by rblxcollin** [comment]
You can try using the new Bypass. Tell us if it works, we are always happy about Feedback.

**Comment by Ironbrodiet** [comment]
My district also blocked replit. The bypass doesn't work for me.

**Comment by logieboyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy** [comment]
> You can try using the new Bypass. Tell us if it works, we are always happy about Feedback.

did not work

**Comment by logieboyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy** [comment]
whoops

**Comment by Ironbrodiet** [comment]
?

**Comment by Cerealistic** [comment]
Sorry, I haven't been really into my website recently. I am working on EaglercraftY, which is the 1.9.4 version of eaglercraft.

**Comment by Ironbrodiet** [comment]
Right... and I'm working on Eaglercraftඞ, the 1.69.420 version of eaglercraft.

**Comment by Cerealistic** [comment]
Seriously? Get a life. Get off of GitHub. Allow the intelligent people to work. I actually am, and just because you don't understand an ounce of Java doesn't mean anything.

**Comment by Ironbrodiet** [comment]
LOL

**Comment by Ironbrodiet** [comment]
Actually, tell me how it works. Lax1dude hasn't even finished 1.8 yet. How are you working on 1.9?

**Comment by Cerealistic** [comment]
Okay, so basically we take code from 1.5.2 eaglercraft and cross-reference it with 1.8.8 eaglercraft. Matching components are kept as they are constants in the development. We then develop code *somewhat* like the previous code to link the java application to the html. This then would be early beta. We would then *eventually* come out with server software that allows for multiplayer servers to be created. This might take from 3 months to a year, so lol its gonna be a while.
