### ISSUE TITLE
Want help?

### ISSUE THREAD

**Issue by rblxcollin** [Cerealistic/Cerealistic.github.io#8]
This is a Message to Cerealist
______________________________
Do you want help?
I can help you with this Project.
For Example the CSS doesnt look that great.
I'd be happy to work with you.

**Comment by rblxcollin** [comment]
If u have Discord, add me: `rblxcollin#0001`

**Comment by Cerealistic** [comment]
I sent you a friend request, sure I would be fine with working with you. I will add you to this repository.

**Comment by Cerealistic** [comment]
Would you mind telling my how you found this repository? I don't know how people are finding this.

**Comment by rblxcollin** [comment]
it popped up on my github home page
btw, can you get online on discord?
